// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi1xsInA0x4vy_xVjeuate4vbEIw2MLyM',
    appId: '1:533942350955:web:bc7fdda52c2a93dcc72d2e',
    messagingSenderId: '533942350955',
    projectId: 'watch-hub-22ef8',
    authDomain: 'watch-hub-22ef8.firebaseapp.com',
    storageBucket: 'watch-hub-22ef8.firebasestorage.app',
    measurementId: 'G-ZV2NXF2W04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANFmzVtUCWw6ZVedosDCNZhK9BXNgL2vI',
    appId: '1:533942350955:android:3c757f31ccc82371c72d2e',
    messagingSenderId: '533942350955',
    projectId: 'watch-hub-22ef8',
    storageBucket: 'watch-hub-22ef8.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY8HPlAwzoFZSwqr3cprHmKEth9jtaXsM',
    appId: '1:533942350955:ios:51c3e90ea5016865c72d2e',
    messagingSenderId: '533942350955',
    projectId: 'watch-hub-22ef8',
    storageBucket: 'watch-hub-22ef8.firebasestorage.app',
    iosBundleId: 'com.example.watchhub',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY8HPlAwzoFZSwqr3cprHmKEth9jtaXsM',
    appId: '1:533942350955:ios:51c3e90ea5016865c72d2e',
    messagingSenderId: '533942350955',
    projectId: 'watch-hub-22ef8',
    storageBucket: 'watch-hub-22ef8.firebasestorage.app',
    iosBundleId: 'com.example.watchhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi1xsInA0x4vy_xVjeuate4vbEIw2MLyM',
    appId: '1:533942350955:web:de62e3937a699e56c72d2e',
    messagingSenderId: '533942350955',
    projectId: 'watch-hub-22ef8',
    authDomain: 'watch-hub-22ef8.firebaseapp.com',
    storageBucket: 'watch-hub-22ef8.firebasestorage.app',
    measurementId: 'G-667T5W0MFH',
  );

}